// @ts-nocheck
// This file is autogenerated by registry/scripts/build.mts
// Do not edit this file directly.
import * as React from "react";

export const ExamplesIndex: Record<string, Record<string, any>> = {
  "analyzing-image-demo": {
    name: "analyzing-image-demo",
    filePath: "registry/examples/analyzing-image-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./analyzing-image-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "analyzing-image-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "arc-demo": {
    name: "arc-demo",
    filePath: "registry/examples/arc-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./arc-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "arc-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "bars-demo": {
    name: "bars-demo",
    filePath: "registry/examples/bars-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./bars-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "bars-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "bouncing-dots-demo": {
    name: "bouncing-dots-demo",
    filePath: "registry/examples/bouncing-dots-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./bouncing-dots-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "bouncing-dots-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "classic-demo": {
    name: "classic-demo",
    filePath: "registry/examples/classic-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./classic-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "classic-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dots-demo": {
    name: "dots-demo",
    filePath: "registry/examples/dots-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./dots-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "dots-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dual-arc-demo": {
    name: "dual-arc-demo",
    filePath: "registry/examples/dual-arc-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./dual-arc-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "dual-arc-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "pulse-demo": {
    name: "pulse-demo",
    filePath: "registry/examples/pulse-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./pulse-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "pulse-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "pulse-dot-demo": {
    name: "pulse-dot-demo",
    filePath: "registry/examples/pulse-dot-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./pulse-dot-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "pulse-dot-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "ring-demo": {
    name: "ring-demo",
    filePath: "registry/examples/ring-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./ring-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "ring-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "skeleton-demo": {
    name: "skeleton-demo",
    filePath: "registry/examples/skeleton-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./skeleton-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "skeleton-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spokes-demo": {
    name: "spokes-demo",
    filePath: "registry/examples/spokes-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./spokes-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "spokes-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "swirling-demo": {
    name: "swirling-demo",
    filePath: "registry/examples/swirling-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./swirling-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "swirling-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "terminal-demo": {
    name: "terminal-demo",
    filePath: "registry/examples/terminal-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./terminal-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "terminal-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "text-blink-demo": {
    name: "text-blink-demo",
    filePath: "registry/examples/text-blink-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./text-blink-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "text-blink-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "text-dots-demo": {
    name: "text-dots-demo",
    filePath: "registry/examples/text-dots-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./text-dots-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "text-dots-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "text-shimmer-demo": {
    name: "text-shimmer-demo",
    filePath: "registry/examples/text-shimmer-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./text-shimmer-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "text-shimmer-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "text-shimmer-wave-demo": {
    name: "text-shimmer-wave-demo",
    filePath: "registry/examples/text-shimmer-wave-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./text-shimmer-wave-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "text-shimmer-wave-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "typing-demo": {
    name: "typing-demo",
    filePath: "registry/examples/typing-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./typing-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "typing-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "wave-demo": {
    name: "wave-demo",
    filePath: "registry/examples/wave-demo.tsx",
    component: React.lazy(async () => {
      const mod = await import("./wave-demo.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || "wave-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
};
